default: &default
  adapter: mysql2
  encoding: utf8
  username: cutyremon
  password: 
  host: localhost
  port: 3306

development:
  <<: *default
  database: development_db_name

test:
  <<: *default
  database: test_db_name

production:
  <<: *default
  database: production_db_name
